<div class="splash-container">
    <div class="splash">
        <h1 class="splash-head">Get Started with<br>SkayaPHP!</h1>
        <p class="splash-subhead">
        </p>
        <p>
            <a href="#wrapper" class="pure-button pure-button-primary">Get Started</a>
        </p>
    </div>
</div>

<div class="content-wrapper" id="wrapper">
    <div class="content">
        <h2 class="content-head is-center">Make sure You setted the enviroment right.</h2>

        <div class="pure-g">
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                
                <h3 class="content-subhead <?=$dbconnection ? "success" : "error"; ?>">
                    <?=$dbconnection ? "Correctly connected to the database" : 
                        "You aren't connected to any database. Have you checked the config file?"; ?>
                </h3>
                <p>
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead <?=$writabletmp ? "success" : "error"; ?>">
                        <?=$writabletmp ? "The tmp folder is writable" : 
                        "I need the tmp folder to be writable!"; ?>
                </h3>
                <p>
                </p>
            </div>
        </div>
    </div>

    <div class="ribbon l-box-lrg pure-g">
        <div class="footer-tab pure-u pure-u-8-24">
        Website: <?=$this->Html->link('Coming soon...','',['class' => 'error','style' => 'text-decoration:none']);?>
        </div>
        <div class="footer-tab pure-u pure-u-8-24">
        Documentation: <?=$this->Html->link('Coming soon...','',['class' => 'error','style' => 'text-decoration:none']);?>
        </div>
        <div class="footer-tab pure-u pure-u-8-24">
        Community: <?=$this->Html->link('Coming soon...','',['class' => 'error','style' => 'text-decoration:none']);?>
        </div>
    </div>
</div>

