<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$this->_pageTitle;?></title>
    <?=$this->Css->link(['pure-min.css','font-awesome.min.css','marketing.css','skayaphp.css']); ?>
</head>
<body>

<div class="header">
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="">SkayaPHP</a>
        <ul class="pure-menu-list">
        </ul>
    </div>
</div>

<?=$this->content();?>

<?php 
if(DEV_MODE == true){
    if(!empty($this->Session->read('errors'))){
        foreach($this->Session->read('errors') as $error){
            echo $error . "<br>\n";
        }
        unset($_SESSION['errors']);
    }
}
?>

</body>
</html>
